name: 'Setup environment'
description: 'Setup environment for HSE FIPL courses'

runs:
  using: "composite"
  steps:
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Cache pip
      uses: actions/cache@v3
      id: cache
      with:
        path: |
          ./venv/
          ~/.local/bin/mystem
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements*.txt') }}
        restore-keys: |
          ${{ runner.os }}-venv-
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        bash config/venv_setup.sh
