name: 'Setup environment'
description: 'Setup environment for HSE FIPL courses'
runs:
  using: "composite"
  steps:
    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: '3.13.11'
    - name: Cache pip
      uses: actions/cache@v4
      id: cache
      with:
        path: |
          ./venv/
          ~/.local/bin/mystem
        key: ${{ env.GITHUB_REPOSITORY }}-${{ env.BRANCH_NAME }}-pip-${{ hashFiles('**/requirements*.txt') }}
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        bash config/venv_setup.sh
